@startuml

!includeurl https://raw.githubusercontent.com/manuvai/plantuml-utils/master/class_diagram_utils.puml

class Grille {
    #int(code)
    #float(mise)
    #member("int[4]", nombresMises)
}

class SuperGrille {
    -int(numeroChance)

}

class Tolo {
    #member("int[4]", numerosTires)
    +void("effectuerTirage()")
    +int("obtenirGain(Grille)")
}

class SuperTolo {
    -int(numeroChance)
    +void("effectuerTirage()")
    +int("obtenirGain(SuperGrille)")
}

extends(SuperTolo, Tolo, up)
extends(SuperGrille, Grille, up)

Tolo *-right- "0..*" Grille : list(Grille, grillesJouees)

@enduml
